lzc-sdk-version: '0.1'
package: com.selfstudio.moltis
version: 0.10.6
min_os_version: 1.3.8
name: Moltis
description: (LazyCat Auto-build) A security-first AI assistant - sandboxed execution, passkeys, MCP & hybrid memory
license: MIT
homepage: https://moltis.org
author: moltis-org
application:
  subdomain: moltis
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://moltis:13131/
services:
  moltis:
    image: registry.lazycat.cloud/invokerlaw/moltis-org/moltis:30611e44ce008765
    environment:
      - MOLTIS_NO_TLS=true
      - MOLTIS_BEHIND_PROXY=true
      - MOLTIS_BIND=0.0.0.0
      - MOLTIS_WEBAUTHN_RP_ID=${LAZYCAT_APP_DOMAIN}
      - MOLTIS_WEBAUTHN_ORIGIN=https://${LAZYCAT_APP_DOMAIN}
    binds:
      - /lzcapp/var/config:/home/moltis/.config/moltis
      - /lzcapp/var/data:/home/moltis/.moltis
      - /lzcapp/var/db:/home/moltis/.local/share/moltis
    setup_script: |
      chown -R moltis:moltis /home/moltis
locales:
  en:
    name: Moltis
    description: (LazyCat Auto-build) A security-first AI assistant - single binary, sandboxed execution, passkeys, MCP & hybrid memory
  zh:
    name: Moltis
    description: （懒猫微服自动构建）安全优先的 AI 助手 - 单一二进制文件，沙箱执行，Passkeys 认证，MCP 支持与混合记忆